### ISSUE TITLE
Error in text search in 't'

### ISSUE THREAD

**Issue by amasawa** [aitsc/alfred.filesearch#2]
10.15.7 
`Error  in workflow 'File Search'
list index out of range`

maybe arises from the python version, but I cannot find any version requirements

**Comment by aitsc** [comment]
Is the second or third step in the [tutorial](https://github.com/aitsc/alfred.filesearch#可能遇到的情况) useful?

**Comment by amasawa** [comment]
Neither worked. And Actually, I tried another released Version but all of them have the same problem.

**Comment by amasawa** [comment]
The bug arises from 
`Library not loaded: /usr/local/opt/pcre/lib/libpcre.1.dylib`
So  it will be fixed when `libpcre.1.dylib` was loaded in `/usr/local/opt/pcre/lib` , not `/usr/local/opt/pcre/lib/intel`
Thank you for ur powerful workflow agagin!
